name: 福井県のデータをGitHubへPush

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn generate:dev
